root: ../data/exp/

seed_offset: 0
num_instances: 10
save_plot: true

instance:
  _target_: MAPPFD.generate_random_instance_grid
  N_min: 3
  N_max: 5
  width: 8
  height: 8
  occupancy_rate: 0.05

solvers:
  - _target_: MAPPFD.simple_solver4
  - _target_: MAPPFD.simple_solver5

verification:
  _target_: MAPPFD.sync_verification
  num_repetition: 20
  failure_prob: 0.3
  max_makespan: 30
