root: ../data/benchmark/01_sync

benchmark:
  _target_: generate_multiple_random_sync_instance_grid_wellformed
  num: 5
  N_min: 3
  N_max: 15
  width: 8
  height: 8
  occupancy_rate: 0

viz:
  _target_: plot_instance
  figsize: 200
  markersize: 8
  markersize_goal: 3
  show_vertex_id: true
  show_agent_id: true
  fontsize: 3
