root: ../data/exp/01_sync

seed_offset: 0
save_plot: false

instances:
  _target_: generate_multiple_random_sync_instance_grid_wellformed
  num: 5
  N_min: 3
  N_max: 8
  width: 8
  height: 8
  occupancy_rate: 0
  max_num_crashes: 0

solvers_common: &solvers_common
  time_limit_sec: 3

solvers:
  - _target_: MAPPFD.planner1
    <<: *solvers_common
    multi_agent_path_planner:
      _target_: MAPPFD.Solver.astar_operator_decomposition

verification:
  _target_: approx_verify_with_local_FD
  max_activation: 30
  num_repetition: 1
  failure_prob: 0.2
