root: ../data/exp/

seed_offset: 0
save_plot: false

instances:
  _target_: generate_multiple_random_sync_instance_grid_wellformed
  num: 5
  N_min: 3
  N_max: 8
  # N: 6
  width: 8
  height: 8
  occupancy_rate: 0
  # max_num_crashes_min: 0
  # max_num_crashes_max: 5

time_limit_sec: 3

solvers_common: &solvers_common
  multi_agent_path_planner:
      _target_: MAPPFD.Solver.astar_operator_decomposition

solvers:
  - _target_: MAPPFD.planner1
    <<: *solvers_common

verification:
  _target_: approx_verify_with_local_FD
  max_activation: 30
  num_repetition: 10
  failure_prob: 0.2

summary:
  - _target_: describe_simply
    VERBOSE: 1
  - _target_: plot_cactus
  - _target_: plot_runtime_vs_max_num_crashes
  - _target_: plot_success_rate_vs_max_num_crashes
  - _target_: open_result_dir
