root: ../data/exp/

seed_offset: 0
VERBOSE: 1

instances:
  _target_: generate_multiple_random_sync_instance_grid_wellformed
  num: 1
  VERBOSE: 1
  N_min: 10
  N_max: 30
  width: 30
  height: 30
  occupancy_rate: 0
  # max_num_crashes_min: 1
  # max_num_crashes_max: 5
  max_num_crashes: 2

solvers_common: &solvers_common
  VERBOSE: 0
  timestep_limit: 100
  avoid_duplicates_backup: true
  multi_agent_path_planner:
    _target_: MAPPFD.Solver.RPP_refine

time_limit_sec: 10

solvers:
  - _target_: MAPPFD.planner1
    <<: *solvers_common
    search_style: "CRITICAL_SECTIONS"

verification:
  _target_: approx_verify_with_local_FD
  max_activation: 100
  num_repetition: 10
  failure_prob: 0.01

visualization:
  _target_: plot_solution
  markersize: 4

summary:
  - _target_: describe_simply
    VERBOSE: 1
  - _target_: plot_cactus
  - _target_: plot_runtime_vs_max_num_crashes
  - _target_: plot_success_rate_vs_max_num_crashes
  - _target_: plot_failure_reasons
  - _target_: plot_N_vs_success_rate
  # - _target_: open_result_dir
