name: CI

on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'src/**'
      - 'test/**'
      - 'scripts/*.jl'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.7']
        os: [macos-10.15, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: "setup julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/cache@v1
        with:
          cache-registries: "true"
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        timeout-minutes: 5
